[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@uniswap/v3-core/=./lib/v3-core",
    "@openzeppelin/=./lib/openzeppelin-contracts"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
